### ISSUE TITLE
Do you have a good way to import existing items into state?

### ISSUE THREAD

**Issue by Poltergeisen** [mhosker/terraform-azure-management-groups#1]
For some reason terraform doesn't pick up that I have existing management groups so I can't easily generate the imports via the code. 

Do you have a way to generate import statements from this variable that is set?

**Comment by mhosker** [comment]
Hi,

Sorry for the delay.

If you were wanting to import, based on the `example.tf` it would be something like:

```console
terraform import module.management-groups.azurerm_management_group.level_2["MH/MH-Prod"] /providers/Microsoft.Management/managementGroups/MH-Prod
```

Hope that helps?

Mike :)

**Comment by Poltergeisen** [comment]
Hi, yes, that helps, but I was looking for an import block. I've been playing around with something like this:

```
import {
  for_each = local.level_2

  id = "/providers/Microsoft.Management/managementGroups/${basename(each.key)}"
  to = module.base.azurerm_management_group.level_2[each.key]
}
```

I'm not sure what's going on, but for linux it's not working. For my windows machine locally everything seems to import fine...

The message I get on linux:

```
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to
│ "module.base.azurerm_management_group.level_1[\"lhg\"]", the provider
│ detected that no object exists with the given id. Only pre-existing objects
│ can be imported; check that the id is correct and that it is associated
│ with the provider's configured region or endpoint, or use "terraform apply"
│ to create a new remote object for this resource.

```


I'm not really sure why this works on windows. I was thinking maybe because of the "\\"?


My windows run produces this:
![image](https://github.com/user-attachments/assets/6e4b4f06-3ef2-4c33-9b6d-f4ed36de22de)

**Comment by Poltergeisen** [comment]
Sorry, somewhat debugging here as I type, sorry to blow you up.

I'm just not sure at all why this import statement isn't working in AZDO on my build agent....

![image](https://github.com/user-attachments/assets/479c695b-f64a-405b-855b-10c6371b5bbb)

As you can see it seems to inject `\` characters into the module, or maybe the terraform output does that. Either way it's not working

I commented out the first level of import statements to see what resource it'd try to add. From what I can tell the names match up

**Comment by Poltergeisen** [comment]
I also created this issue here, im not really sure where the problem is on my build agents. I'm guessing it has something to do with these build tasks. 

https://github.com/microsoft/azure-pipelines-terraform/issues/258


Bah.... been doing more tracing.... I think it's just permissions issues. I'll close this if I get it working

**Comment by Poltergeisen** [comment]
This was a permissions error. Thank you again for the help.

**Comment by mhosker** [comment]
Glad you got this resolved and thanks for commenting the outcome :)
